create table public.maintenances (
  id bigint generated by default as identity,
  "vehicleId" bigint not null,
  "noteId" bigint null,
  cost integer not null,
  kilometers integer null,
  constraint maintenances_pkey primary key (id),
  constraint maintenances_noteId_fkey foreign key ("noteId") references notes (id),
    constraint maintenances_vehicleId_fkey foreign key ("vehicleId") references vehicles (id)
) tablespace pg_default;

create table public.notes (
  id bigint generated by default as identity,
  type character varying not null default ''::character varying,
  description character varying null,
  photo character varying null,
  date date not null,
  constraint notes_pkey primary key (id)
) tablespace pg_default;

create table public.pets (
  id bigint generated by default as identity,
  "noteId" bigint not null,
  name character varying not null,
  breed character varying not null,
  constraint pets_pkey primary key (id),
  constraint pets_noteId_fkey foreign key ("noteId") references notes (id)
) tablespace pg_default;

create table public.procedures (
  id bigint generated by default as identity,
  "petId" bigint not null,
  "noteId" bigint not null,
  cost integer not null,
  weight smallint null,
  "nextDate" date null,
  constraint procedures_pkey primary key (id),
  constraint procedures_noteId_fkey foreign key ("noteId") references notes (id),
  constraint procedures_petId_fkey foreign key ("petId") references pets (id)
) tablespace pg_default;

create table public.vehicles (
  id bigint generated by default as identity,
  "noteId" bigint not null,
  "plateNumber" character varying not null,
  brand character varying not null,
  model smallint not null,
  constraint vehicles_pkey primary key (id),
  constraint vehicles_noteId_fkey foreign key ("noteId") references notes (id)
) tablespace pg_default;
